//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrowaveNetworksTests.TouchstoneTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleReaderFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleReaderFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrowaveNetworksTests.TouchstoneTests.SampleReaderFiles", typeof(SampleReaderFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! 4-port S-parameter data, taken at three frequency points
        ///! note that data points need not be aligned
        ///# GHz S MA R 50
        ///5.00000 0.60 161.24 0.40 -42.20 0.42 -66.58 0.53 -79.34 !row 1
        ///        0.40 -42.20 0.60 161.20 0.53 -79.34 0.42 -66.58 !row 2
        ///        0.42 -66.58 0.53 -79.34 0.60 161.24 0.40 -42.20 !row 3
        ///        0.53 -79.34 0.42 -66.58 0.40 -42.20 0.60 161.24 !row 4
        ///6.00000 0.57 150.37 0.40 -44.34 0.41 -81.24 0.57 -95.77 !row 1
        ///        0.40 -44.34 0.57 150.37 0.57 -95.77 0.41 -81.24 !row 2
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourPort_v1 {
            get {
                return ResourceManager.GetString("FourPort_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! 4-port S-parameter data
        ///! Default impedance is overridden by the [Reference] keyword arguments
        ///! Data cannot be represented using 1.0 syntax
        ///[Version] 2.0
        ///# GHz S MA R 50
        ///[Number of Ports] 4
        ///[Number of Frequencies] 1
        ///[Reference] 50 75 0.01 0.01
        ///[Matrix Format] Full
        ///[Network Data]
        ///5.00000 0.60 161.24 0.40 -42.20 0.42 -66.58 0.53 -79.34 !row 1
        ///		0.40 -42.20 0.60 161.20 0.53 -79.34 0.42 -66.58 !row 2
        ///		0.42 -66.58 0.53 -79.34 0.60 161.24 0.40 -42.20 !row 3
        ///		0.53 -79.34 0.42 -66.58 0.40 -42.20 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourPort_v2_FullMatrix {
            get {
                return ResourceManager.GetString("FourPort_v2_FullMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! 4-port S-parameter data
        ///! Default impedance is overridden by the [Reference] keyword arguments
        ///! Note that [Reference] arguments are split across two lines
        ///! Data cannot be represented using 1.0 syntax
        ///[Version] 2.0
        ///# GHz S MA R 50
        ///[Number of Ports] 4
        ///[Number of Frequencies] 1
        ///[Reference] 50 75
        ///0.01 0.01
        ///[Matrix Format] Lower
        ///[Network Data]
        ///5.00000 0.60 161.24 !row 1
        ///		0.40 -42.20 0.60 161.20 !row 2
        ///		0.42 -66.58 0.53 -79.34 0.60 161.24 !row 3
        ///		0.53 -79.34 0.42 -66.58 0.40 -42.20 0.60 161. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourPort_v2_LowerMatrix {
            get {
                return ResourceManager.GetString("FourPort_v2_LowerMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! 4-port S-parameter data
        ///! Default impedance is overridden by the [Reference] keyword arguments
        ///! Note that [Reference] arguments are split across two lines
        ///! Data cannot be represented using 1.0 syntax
        ///[Version] 2.0
        ///# GHz S MA R 50
        ///[Number of Ports] 4
        ///[Number of Frequencies] 1
        ///[Reference] 50 75
        ///0.01 0.01
        ///[Matrix Format] Upper
        ///[Network Data]
        ///5.00000 0.60 161.24 0.40 -42.20 0.42 -66.58 0.53 -79.34 !row 1
        ///					0.60 161.20 0.53 -79.34 0.42 -66.58 !row 2
        ///								0.60 161.24 0.40 -42.20 !row 3
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourPort_v2_UpperMatrix {
            get {
                return ResourceManager.GetString("FourPort_v2_UpperMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # MHz S MA R 75
        ///!freq magZ11 angZ11
        ///100 0.99 -4
        ///200 0.80 -22
        ///300 0.707 -45
        ///400 0.40 -62
        ///500 0.01 -89.
        /// </summary>
        internal static string OnePort_v1 {
            get {
                return ResourceManager.GetString("OnePort_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !1-port S-parameter file, multiple frequency points
        ///[Version] 2.0
        ///# MHz S MA
        ///[Number of Ports] 1
        ///[Number of Frequencies] 5
        ///[Reference] 20.0
        ///[Network Data]
        ///!freq ReS11 ImS11
        ///1.0000 0.3926 -0.1211
        ///2.0000 0.3517 -0.3054
        ///3.0000 0.3419 0.3336.
        /// </summary>
        internal static string OnePort_v2 {
            get {
                return ResourceManager.GetString("OnePort_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !6-port component shown; note that all five ports are used in some
        ///!relationship
        ///[Version] 2.0
        ///# MHz S RI R 50
        ///[Number of Ports] 6
        ///[Number of Frequencies] 1
        ///[Reference] 50 75 75 50 0.01 0.01
        ///[Mixed-Mode Order] D2,3 D6,5 C2,3 C6,5 S4 S1
        ///[Network Data]
        ///5.00 8.0 9.0 2.0 -1.0 3.0 -2.0 1.0 3.0 1.0 0.1 0.2 -0.2
        ///2.0 -1.0 7.0 7.0 1.8 -2.0 -1.0 -1.0 -0.5 0.5 0.2 -0.1
        ///3.0 -2.0 1.8 -2.0 5.8 6.0 1.2 0.8 0.9 0.7 0.3 -0.5
        ///1.0 3.0 -1.0 -1.0 1.2 0.8 6.3 8.0 2.0 -0.5 1.5 0.6
        ///1.0 0.1 -0.5 0.5 0.9 0.7 2.0 -0.5 4. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SixPort_v2_MixedMode {
            get {
                return ResourceManager.GetString("SixPort_v2_MixedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !2-port S-parameter file, three frequency points 
        ///# GHz S RI R 50.0 
        ///!freq ReS11 ImS11 ReS21 ImS21 ReS12 ImS12 ReS22 ImS22 
        ///1.0000 0.3926 -0.1211 -0.0004 -0.0022 -0.0003 -0.0021 0.3926 -0.1211 
        ///2.0000 0.3517 -0.3054 -0.0096 -0.0298 -0.0097 -0.0299 0.3517 -0.3054 
        ///10.000 0.3419 0.3336 -0.0134 0.0379 -0.0134 0.0379 0.3420 0.3337 .
        /// </summary>
        internal static string TwoPort_v1 {
            get {
                return ResourceManager.GetString("TwoPort_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !2-port network, S-parameter and noise data
        ///!Default MA format, GHz frequencies, 50 &amp; 25 ohm reference, S-parameters
        ///[Version] 2.0
        ///#
        ///[Number of Ports] 2
        ///[Two-Port Data Order] 12_21
        ///[Number of Frequencies] 2
        ///[Reference] 50 25.0
        ///[Network Data]
        ///2 .95 -26 .04 76 3.57 157 .66 -14
        ///22 .60 -144 .14 40 1.30 40 .56 -85
        ///[End].
        /// </summary>
        internal static string TwoPort_v2_12_21 {
            get {
                return ResourceManager.GetString("TwoPort_v2_12_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !2-port network, S-parameter and noise data
        ///!Default MA format, GHz frequencies, 50 &amp; 25 ohm reference, S-parameters
        ///[Version] 2.0
        ///#
        ///[Number of Ports] 2
        ///[Two-Port Data Order] 21_12
        ///[Number of Frequencies] 2
        ///[Reference]
        ///50 25.0
        ///[Network Data]
        ///2 .95 -26 3.57 157 .04 76 .66 -14
        ///22 .60 -144 1.30 40 .14 40 .56 -85
        ///.
        /// </summary>
        internal static string TwoPort_v2_21_12 {
            get {
                return ResourceManager.GetString("TwoPort_v2_21_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !2-port network, S-parameter and noise data
        ///!Default MA format, GHz frequencies, 50 &amp; 25 ohm reference, S-parameters
        ///[Version] 2.0
        ///#
        ///[Number of Ports] 2
        ///[Number of Frequencies] 2
        ///[Reference] 50 25.0
        ///[Network Data]
        ///2 .95 -26 3.57 157 .04 76 .66 -14
        ///22 .60 -144 1.30 40 .14 40 .56 -85
        ///[End].
        /// </summary>
        internal static string TwoPort_v2_No_Order {
            get {
                return ResourceManager.GetString("TwoPort_v2_No_Order", resourceCulture);
            }
        }
    }
}
